### ISSUE TITLE
Using new 'get' method

### ISSUE THREAD

**Issue by pzolla** [textadventures/squiffy#41] opened 2015-02-21 14:48 UTC
If I run the attributes example using native Squiffy and use browser console:
```
$("#squiffy").squiffy("get", "story")
```
returns null.  If I make the squiffy variable global and run
```
squiffy.story
```
the object is returned.

I had similar result when testing for 'squiffy.ui.settings.persist'.

**Comment by alexwarren** [comment] 2015-02-21 15:25
Those are not attributes! Get and set are for game state, they access the
same values as squiffy.set and squiffy.get.

The JavaScript squiffy object is hidden from external JavaScript by design.
If you want to access it, your current approach of moving it to the global
scope is correct.

**Closed** 2015-03-27 18:40 UTC
