### ISSUE TITLE
Mac compiler broken behavior

### ISSUE THREAD

**Issue by jmechalas** [textadventures/squiffy#76] opened 2018-03-20 23:37 UTC
When this code is compiled on a Windows system, it sets the value of "foo" to 1 and doesn't output anything:

`{@foo=1}`

When this same code is compiled on a Mac, it does not set foo and it prints "null" in the output.

**Comment by loopernow** [comment] 2018-04-20 17:13
The issue is that the Mac version is 5.0 but the code you're referring to was introduced with version 5.1.2. I am assuming that the maintainers do not have a Mac. I tried building the new version of Squiffy myself per some instructions posted on the Squiffy github but it errored out--I think because I don't have xtools. I'm not a programmer so it's all a bit hit-and-miss for me.

You can circumvent the problem by using the command-line version of squiffy to compile your game. Then it will work. It's not ideal but it's a workaround.

Another thought I had was to use something like Wineskin to run the Linux version of Squiffy on my Mac. I tried Winebottler and it wouldn't run.

**Comment by alexwarren** [comment] 2024-09-08 16:08
Closing as this will be resolved with the next release.

**Closed by alexwarren** 2024-09-08 16:08 UTC
